export enum ActionTypes {
    GET_POPULAR_MOVIES = "@@movies/GET_POPULAR_MOVIES",
    GET_POPULAR_MOVIES_SUCCESS = "@@movies/GET_POPULAR_MOVIES_SUCCESS",
    GET_POPULAR_MOVIES_ERROR = "@@movies/GET_POPULAR_MOVIES_ERROR",
}
